//! Auto-update logic for CodeOS.
//!
//! This module integrates with `tauri-plugin-updater` to fetch and install
//! updates from GitHub Releases. The update manifest URL is configured in
//! `tauri.conf.json` under `plugins.updater.endpoints`.
//!
//! # Manifest format (served at the endpoint URL)
//! ```json
//! {
//!   "version": "0.2.0",
//!   "notes": "Bug fixes and performance improvements.",
//!   "pub_date": "2025-01-01T00:00:00Z",
//!   "platforms": {
//!     "darwin-aarch64": {
//!       "signature": "<sig>",
//!       "url": "https://github.com/.../CodeOS_0.2.0_aarch64.dmg.tar.gz"
//!     },
//!     "darwin-x86_64": {
//!       "signature": "<sig>",
//!       "url": "https://github.com/.../CodeOS_0.2.0_x86_64.dmg.tar.gz"
//!     }
//!   }
//! }
//! ```
//!
//! The manifest and each binary asset are signed with the Ed25519 key pair
//! generated by `tauri signer generate`. The public key is embedded in
//! `tauri.conf.json`; the private key is kept secret (CI secret / env var).

use tauri::{AppHandle, Emitter};
use tauri_plugin_updater::UpdaterExt;

#[derive(serde::Serialize, Clone)]
pub struct UpdateStatus {
    pub available: bool,
    pub version: Option<String>,
    pub notes: Option<String>,
    pub error: Option<String>,
}

/// Check for updates and emit an event to the frontend with the result.
/// Call from the frontend via `invoke("check_for_updates")`.
#[tauri::command]
pub async fn check_for_updates(app: AppHandle) -> Result<UpdateStatus, String> {
    let updater = app
        .updater_builder()
        .build()
        .map_err(|e| format!("Updater init failed: {}", e))?;

    match updater.check().await {
        Ok(Some(update)) => {
            let status = UpdateStatus {
                available: true,
                version: Some(update.version.clone()),
                notes: update.body.clone(),
                error: None,
            };
            // Emit to any listening frontend windows.
            let _ = app.emit("update-available", status.clone());
            Ok(status)
        }
        Ok(None) => Ok(UpdateStatus {
            available: false,
            version: None,
            notes: None,
            error: None,
        }),
        Err(e) => Ok(UpdateStatus {
            available: false,
            version: None,
            notes: None,
            error: Some(e.to_string()),
        }),
    }
}

/// Download and install the pending update.
/// Progress events are emitted to the frontend as `update-progress`.
#[tauri::command]
pub async fn install_update(app: AppHandle) -> Result<(), String> {
    let updater = app
        .updater_builder()
        .build()
        .map_err(|e| format!("Updater init failed: {}", e))?;

    let update = updater
        .check()
        .await
        .map_err(|e| e.to_string())?
        .ok_or_else(|| "No update available".to_string())?;

    let _ = app.emit("update-downloading", update.version.clone());

    update
        .download_and_install(
            |downloaded, total| {
                let pct = total.map(|t| (downloaded as f64 / t as f64 * 100.0) as u32);
                let _ = app.emit("update-progress", pct);
            },
            || {
                let _ = app.emit("update-installing", ());
            },
        )
        .await
        .map_err(|e| e.to_string())?;

    Ok(())
}
